#### stage 1 #####
FROM node:20.11-alpine as node

WORKDIR /FE_DIWA_WEBVIEW

COPY package*.json ./FE_DIWA_WEBVIEW

COPY .env.dev-docker /FE_DIWA_WEBVIEW/

COPY src/component/configuration* /FE_DIWA_WEBVIEW

COPY src/component/lottieFiles /FE_DIWA_WEBVIEW
# COPY  postcss.config.js /FE_DIWA_WEBVIEW/

# COPY tailwind.config.js /FE_DIWA_WEBVIEW/

# COPY vite.config.js /FE_DIWA_WEBVIEW/

RUN npm install -g npm@10.5.0

COPY . /FE_DIWA_WEBVIEW/

CMD [ "npm", "run", "devdocker" ]

# CMD [ "npm", "run", "preview" ]

FROM nginx:1.17.1-alpine
RUN apk update && apk add bash && apk add less && apk add nano

RUN rm /usr/share/nginx/html/*
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=node /FE_DIWA_WEBVIEW /usr/share/nginx/html

